/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Cuisine = IDL.Variant({
  'bar' : IDL.Null,
  'pub' : IDL.Null,
  'fineDining' : IDL.Null,
  'seafood' : IDL.Null,
  'steakhouse' : IDL.Null,
  'cafe' : IDL.Null,
  'deli' : IDL.Null,
  'winery' : IDL.Null,
  'sandwiches' : IDL.Null,
  'mexican' : IDL.Null,
  'hybrid' : IDL.Null,
  'italian' : IDL.Null,
  'hotelRestaurant' : IDL.Null,
  'market' : IDL.Null,
  'pizza' : IDL.Null,
  'burger' : IDL.Null,
  'barbecue' : IDL.Null,
  'asianFusion' : IDL.Null,
  'coffeeShop' : IDL.Null,
  'brewery' : IDL.Null,
});
export const VibeAttributes = IDL.Record({
  'dogFriendly' : IDL.Bool,
  'familyFriendly' : IDL.Bool,
  'dateNightFriendly' : IDL.Bool,
  'artCraftsFocused' : IDL.Bool,
  'perfectLighting' : IDL.Bool,
  'brightOpenSpaces' : IDL.Bool,
  'liveMusic' : IDL.Bool,
  'themedDrinks' : IDL.Bool,
  'fruitInfusedRecipes' : IDL.Bool,
  'mountainViews' : IDL.Bool,
  'workFriendly' : IDL.Bool,
  'fruitCiderOptions' : IDL.Bool,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Restaurant = IDL.Record({
  'isGreatForDate' : IDL.Bool,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPetFriendly' : IDL.Bool,
  'imageURL' : IDL.Text,
  'address' : IDL.Text,
  'cuisine' : Cuisine,
  'isHiddenGem' : IDL.Bool,
  'isNearRiverfrontTrail' : IDL.Bool,
  'location' : IDL.Text,
  'isPalisadeFruitSeason' : IDL.Bool,
  'vibeAttributes' : VibeAttributes,
  'coordinates' : Coordinates,
  'seasonalMonths' : IDL.Vec(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDateNightRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getPetFriendlyRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getRestaurantByName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Restaurant)],
      ['query'],
    ),
  'getRestaurantsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'getRestaurantsNearTrail' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByCuisine' : IDL.Func([Cuisine], [IDL.Vec(Restaurant)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Cuisine = IDL.Variant({
    'bar' : IDL.Null,
    'pub' : IDL.Null,
    'fineDining' : IDL.Null,
    'seafood' : IDL.Null,
    'steakhouse' : IDL.Null,
    'cafe' : IDL.Null,
    'deli' : IDL.Null,
    'winery' : IDL.Null,
    'sandwiches' : IDL.Null,
    'mexican' : IDL.Null,
    'hybrid' : IDL.Null,
    'italian' : IDL.Null,
    'hotelRestaurant' : IDL.Null,
    'market' : IDL.Null,
    'pizza' : IDL.Null,
    'burger' : IDL.Null,
    'barbecue' : IDL.Null,
    'asianFusion' : IDL.Null,
    'coffeeShop' : IDL.Null,
    'brewery' : IDL.Null,
  });
  const VibeAttributes = IDL.Record({
    'dogFriendly' : IDL.Bool,
    'familyFriendly' : IDL.Bool,
    'dateNightFriendly' : IDL.Bool,
    'artCraftsFocused' : IDL.Bool,
    'perfectLighting' : IDL.Bool,
    'brightOpenSpaces' : IDL.Bool,
    'liveMusic' : IDL.Bool,
    'themedDrinks' : IDL.Bool,
    'fruitInfusedRecipes' : IDL.Bool,
    'mountainViews' : IDL.Bool,
    'workFriendly' : IDL.Bool,
    'fruitCiderOptions' : IDL.Bool,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Restaurant = IDL.Record({
    'isGreatForDate' : IDL.Bool,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPetFriendly' : IDL.Bool,
    'imageURL' : IDL.Text,
    'address' : IDL.Text,
    'cuisine' : Cuisine,
    'isHiddenGem' : IDL.Bool,
    'isNearRiverfrontTrail' : IDL.Bool,
    'location' : IDL.Text,
    'isPalisadeFruitSeason' : IDL.Bool,
    'vibeAttributes' : VibeAttributes,
    'coordinates' : Coordinates,
    'seasonalMonths' : IDL.Vec(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDateNightRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getPetFriendlyRestaurants' : IDL.Func(
        [],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'getRestaurantByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'getRestaurantsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'getRestaurantsNearTrail' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByCuisine' : IDL.Func([Cuisine], [IDL.Vec(Restaurant)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };