/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Restaurant = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'cuisine' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'searchByCuisine' : IDL.Func([IDL.Text], [IDL.Vec(Restaurant)], ['query']),
  'searchByName' : IDL.Func([IDL.Text], [IDL.Opt(Restaurant)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Restaurant = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'cuisine' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'searchByCuisine' : IDL.Func([IDL.Text], [IDL.Vec(Restaurant)], ['query']),
    'searchByName' : IDL.Func([IDL.Text], [IDL.Opt(Restaurant)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };