/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VibeAttributes {
    dogFriendly: boolean;
    familyFriendly: boolean;
    dateNightFriendly: boolean;
    artCraftsFocused: boolean;
    perfectLighting: boolean;
    brightOpenSpaces: boolean;
    liveMusic: boolean;
    themedDrinks: boolean;
    fruitInfusedRecipes: boolean;
    mountainViews: boolean;
    workFriendly: boolean;
    fruitCiderOptions: boolean;
}
export interface Restaurant {
    isGreatForDate: boolean;
    contact: string;
    name: string;
    description: string;
    isPetFriendly: boolean;
    imageURL: string;
    address: string;
    cuisine: Cuisine;
    isHiddenGem: boolean;
    isNearRiverfrontTrail: boolean;
    location: string;
    isPalisadeFruitSeason: boolean;
    vibeAttributes: VibeAttributes;
    coordinates: Coordinates;
    seasonalMonths: Array<bigint>;
}
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface UserProfile {
    name: string;
}
export enum Cuisine {
    bar = "bar",
    pub = "pub",
    fineDining = "fineDining",
    seafood = "seafood",
    steakhouse = "steakhouse",
    cafe = "cafe",
    deli = "deli",
    winery = "winery",
    sandwiches = "sandwiches",
    mexican = "mexican",
    hybrid = "hybrid",
    italian = "italian",
    hotelRestaurant = "hotelRestaurant",
    market = "market",
    pizza = "pizza",
    burger = "burger",
    barbecue = "barbecue",
    asianFusion = "asianFusion",
    coffeeShop = "coffeeShop",
    brewery = "brewery"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllRestaurants(): Promise<Array<Restaurant>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDateNightRestaurants(): Promise<Array<Restaurant>>;
    getPetFriendlyRestaurants(): Promise<Array<Restaurant>>;
    getRestaurantByName(name: string): Promise<Restaurant | null>;
    getRestaurantsByLocation(location: string): Promise<Array<Restaurant>>;
    getRestaurantsNearTrail(): Promise<Array<Restaurant>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchByCuisine(cuisine: Cuisine): Promise<Array<Restaurant>>;
}
import type { Coordinates as _Coordinates, Cuisine as _Cuisine, Restaurant as _Restaurant, UserProfile as _UserProfile, UserRole as _UserRole, VibeAttributes as _VibeAttributes } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRestaurants();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRestaurants();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDateNightRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDateNightRestaurants();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDateNightRestaurants();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPetFriendlyRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPetFriendlyRestaurants();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPetFriendlyRestaurants();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantByName(arg0: string): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantByName(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantByName(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantsByLocation(arg0: string): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantsByLocation(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantsByLocation(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantsNearTrail(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantsNearTrail();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantsNearTrail();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchByCuisine(arg0: Cuisine): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByCuisine(to_candid_Cuisine_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByCuisine(to_candid_Cuisine_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cuisine_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cuisine): Cuisine {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Restaurant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Restaurant {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Restaurant | null {
    return value.length === 0 ? null : from_candid_Restaurant_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isGreatForDate: boolean;
    contact: string;
    name: string;
    description: string;
    isPetFriendly: boolean;
    imageURL: string;
    address: string;
    cuisine: _Cuisine;
    isHiddenGem: boolean;
    isNearRiverfrontTrail: boolean;
    location: string;
    isPalisadeFruitSeason: boolean;
    vibeAttributes: _VibeAttributes;
    coordinates: _Coordinates;
    seasonalMonths: Array<bigint>;
}): {
    isGreatForDate: boolean;
    contact: string;
    name: string;
    description: string;
    isPetFriendly: boolean;
    imageURL: string;
    address: string;
    cuisine: Cuisine;
    isHiddenGem: boolean;
    isNearRiverfrontTrail: boolean;
    location: string;
    isPalisadeFruitSeason: boolean;
    vibeAttributes: VibeAttributes;
    coordinates: Coordinates;
    seasonalMonths: Array<bigint>;
} {
    return {
        isGreatForDate: value.isGreatForDate,
        contact: value.contact,
        name: value.name,
        description: value.description,
        isPetFriendly: value.isPetFriendly,
        imageURL: value.imageURL,
        address: value.address,
        cuisine: from_candid_Cuisine_n6(_uploadFile, _downloadFile, value.cuisine),
        isHiddenGem: value.isHiddenGem,
        isNearRiverfrontTrail: value.isNearRiverfrontTrail,
        location: value.location,
        isPalisadeFruitSeason: value.isPalisadeFruitSeason,
        vibeAttributes: value.vibeAttributes,
        coordinates: value.coordinates,
        seasonalMonths: value.seasonalMonths
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bar: null;
} | {
    pub: null;
} | {
    fineDining: null;
} | {
    seafood: null;
} | {
    steakhouse: null;
} | {
    cafe: null;
} | {
    deli: null;
} | {
    winery: null;
} | {
    sandwiches: null;
} | {
    mexican: null;
} | {
    hybrid: null;
} | {
    italian: null;
} | {
    hotelRestaurant: null;
} | {
    market: null;
} | {
    pizza: null;
} | {
    burger: null;
} | {
    barbecue: null;
} | {
    asianFusion: null;
} | {
    coffeeShop: null;
} | {
    brewery: null;
}): Cuisine {
    return "bar" in value ? Cuisine.bar : "pub" in value ? Cuisine.pub : "fineDining" in value ? Cuisine.fineDining : "seafood" in value ? Cuisine.seafood : "steakhouse" in value ? Cuisine.steakhouse : "cafe" in value ? Cuisine.cafe : "deli" in value ? Cuisine.deli : "winery" in value ? Cuisine.winery : "sandwiches" in value ? Cuisine.sandwiches : "mexican" in value ? Cuisine.mexican : "hybrid" in value ? Cuisine.hybrid : "italian" in value ? Cuisine.italian : "hotelRestaurant" in value ? Cuisine.hotelRestaurant : "market" in value ? Cuisine.market : "pizza" in value ? Cuisine.pizza : "burger" in value ? Cuisine.burger : "barbecue" in value ? Cuisine.barbecue : "asianFusion" in value ? Cuisine.asianFusion : "coffeeShop" in value ? Cuisine.coffeeShop : "brewery" in value ? Cuisine.brewery : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Array<Restaurant> {
    return value.map((x)=>from_candid_Restaurant_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Cuisine_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cuisine): _Cuisine {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cuisine): {
    bar: null;
} | {
    pub: null;
} | {
    fineDining: null;
} | {
    seafood: null;
} | {
    steakhouse: null;
} | {
    cafe: null;
} | {
    deli: null;
} | {
    winery: null;
} | {
    sandwiches: null;
} | {
    mexican: null;
} | {
    hybrid: null;
} | {
    italian: null;
} | {
    hotelRestaurant: null;
} | {
    market: null;
} | {
    pizza: null;
} | {
    burger: null;
} | {
    barbecue: null;
} | {
    asianFusion: null;
} | {
    coffeeShop: null;
} | {
    brewery: null;
} {
    return value == Cuisine.bar ? {
        bar: null
    } : value == Cuisine.pub ? {
        pub: null
    } : value == Cuisine.fineDining ? {
        fineDining: null
    } : value == Cuisine.seafood ? {
        seafood: null
    } : value == Cuisine.steakhouse ? {
        steakhouse: null
    } : value == Cuisine.cafe ? {
        cafe: null
    } : value == Cuisine.deli ? {
        deli: null
    } : value == Cuisine.winery ? {
        winery: null
    } : value == Cuisine.sandwiches ? {
        sandwiches: null
    } : value == Cuisine.mexican ? {
        mexican: null
    } : value == Cuisine.hybrid ? {
        hybrid: null
    } : value == Cuisine.italian ? {
        italian: null
    } : value == Cuisine.hotelRestaurant ? {
        hotelRestaurant: null
    } : value == Cuisine.market ? {
        market: null
    } : value == Cuisine.pizza ? {
        pizza: null
    } : value == Cuisine.burger ? {
        burger: null
    } : value == Cuisine.barbecue ? {
        barbecue: null
    } : value == Cuisine.asianFusion ? {
        asianFusion: null
    } : value == Cuisine.coffeeShop ? {
        coffeeShop: null
    } : value == Cuisine.brewery ? {
        brewery: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
